apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritwin-frontend-deployment
  namespace: agritwin-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agritwin-frontend
  template:
    metadata:
      labels:
        app: agritwin-frontend
    spec:
      containers:
        - name: agritwin-frontend
          image: agritwin/fe:v1.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: agritwin-frontend-config